### ISSUE TITLE
Generated menu.xml is showing "reconfigure" and "exit" only.

### ISSUE THREAD

**Issue by ahmadraniri1994** [labwc/labwc-menu-gnome3#1]
- Labwc latest master.
- Archlinux.
Thanks.

**Comment by johanmalm** [comment]
Have you installed gnome-menus?

**Comment by ahmadraniri1994** [comment]
> Have you installed gnome-menus?

Yeah, I have gnome-menus 3.36.0-1

**Comment by ahmadraniri1994** [comment]
I end up copy the generated menu.xml manually to my previous / stock menu.xml , and it seems work. Thanks.
